version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/newww
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 720
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 720
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 10
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
